# Generated by Django 3.1.1 on 2020-09-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200919_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='contact',
        ),
    ]
